# Generated by Django 4.1 on 2023-04-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_orders_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.shipping"
            ),
        ),
    ]
