# Generated by Django 4.1 on 2023-04-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_orders_shipping"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="currency",),
        migrations.RemoveField(model_name="payment", name="currency_currency",),
    ]
