# Generated by Django 4.1 on 2023-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_payment_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out For Shipping", "Out For Shipping"),
                    ("Completed", "Completed"),
                    ("cancel", "cancel"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
