# Generated by Django 4.1 on 2023-05-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="uploads\\pf.jpg", null=True, upload_to="images"
            ),
        ),
    ]
