# Generated by Django 4.1 on 2023-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_myaddress"),
    ]

    operations = [
        migrations.RemoveField(model_name="myaddress", name="email",),
        migrations.RemoveField(model_name="shipping", name="email",),
    ]
