# Generated by Django 4.1 on 2023-06-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_orderscancelled_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderscancelled',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderz'),
        ),
        migrations.AlterField(
            model_name='orderscancelled',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
